//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_course_design.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTTABLE
    {
        public string COMMENT_ID { get; set; }
        public Nullable<System.DateTime> COMMENT_DATE { get; set; }
        public string CONTENT { get; set; }
    
        public virtual USER_COMMENT_REPOSITORY USER_COMMENT_REPOSITORY { get; set; }
        public virtual USER_COMMENT_USER USER_COMMENT_USER { get; set; }
    }
}
