//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_course_design.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILETABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FILETABLE()
        {
            this.FILE_FILE = new HashSet<FILE_FILE>();
            this.FILE_FILE1 = new HashSet<FILE_FILE>();
            this.REPOSITORies = new HashSet<REPOSITORY>();
        }
    
        public string FILE_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string PATH { get; set; }
        public string FILE_NAME { get; set; }
        public string FILE_TYPE { get; set; }
        public Nullable<int> FILE_STATE { get; set; }
        public Nullable<int> FILE_SIZE { get; set; }
        public Nullable<int> FILE_DEEP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE_FILE> FILE_FILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FILE_FILE> FILE_FILE1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REPOSITORY> REPOSITORies { get; set; }
    }
}
