//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_course_design.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILE_FILE
    {
        public string FILE_ID1 { get; set; }
        public string FILE_ID2 { get; set; }
        public string FILE_FILE_ID { get; set; }
    
        public virtual FILETABLE FILETABLE { get; set; }
        public virtual FILETABLE FILETABLE1 { get; set; }
    }
}
