//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_course_design.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KUXIANGDATAEntities : DbContext
    {
        public KUXIANGDATAEntities()
            : base("name=KUXIANGDATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMMENTTABLE> COMMENTTABLEs { get; set; }
        public virtual DbSet<FILE_FILE> FILE_FILE { get; set; }
        public virtual DbSet<FILETABLE> FILETABLEs { get; set; }
        public virtual DbSet<MESSAGE> MESSAGEs { get; set; }
        public virtual DbSet<REPOSITORY> REPOSITORies { get; set; }
        public virtual DbSet<USER_COMMENT_REPOSITORY> USER_COMMENT_REPOSITORY { get; set; }
        public virtual DbSet<USER_COMMENT_USER> USER_COMMENT_USER { get; set; }
        public virtual DbSet<USER_REPOSITORY_LOOKHISTORY> USER_REPOSITORY_LOOKHISTORY { get; set; }
        public virtual DbSet<USER_REPOSITORY_OPERATION> USER_REPOSITORY_OPERATION { get; set; }
        public virtual DbSet<USER_REPOSITORY_RELATIONSHIP> USER_REPOSITORY_RELATIONSHIP { get; set; }
        public virtual DbSet<USER_USER> USER_USER { get; set; }
        public virtual DbSet<USERTABLE> USERTABLEs { get; set; }
    }
}
