//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database_course_design.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE
    {
        public string MESSAGE_ID { get; set; }
        public Nullable<System.DateTime> MESSAGE_DATE { get; set; }
        public string MESSAGE_CONTENT { get; set; }
        public string RECEIVER_ID { get; set; }
    
        public virtual USERTABLE USERTABLE { get; set; }
    }
}
